// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpobzmfjkxffnpddisrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indwb2J6bWZqa3hmZm5wZGRpc3JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3OTEwMDMsImV4cCI6MjA3MDM2NzAwM30.aCxgecNsqm81OyDNGHSlGn1Sa_cLldgu8aJubNm07aM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});